version: '3'
services:
  mssql: 
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD}"
    image: registry.gitlab.com/dillonc/mssql-docker:latest
    ports:
      - "8080:8080"
      - "1433:1433"